language: php

php:
  # - 7
  # - 7.1
  - 7.2
  # - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly

global:
  - CI=true
  - CI_ENVIRONMENT=testing

# Recommended by Travis support
sudo: required
dist: precise

env:
  - DB=mysqli
  - DB=postgres

services:
  - memcached
  - mysql
  - postgresql
  - redis-server

script:
  - php vendor/bin/phpunit -v
  # Check files match the standard.
  - ./vendor/bin/phpcs ./public --standard=./vendor/codeigniter4/codeigniter4-standard/Codeigniter4/ruleset.xml
  - ./vendor/bin/phpcs ./application --standard=./vendor/codeigniter4/codeigniter4-standard/Codeigniter4/ruleset.xml
  - ./vendor/bin/phpcs ./system --standard=./vendor/codeigniter4/codeigniter4-standard/Codeigniter4/ruleset.xml

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot;
  - mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test';" -uroot
  - psql -c 'CREATE DATABASE test;' -U postgres

install:
  # Install the other composer deps.
  - composer require squizlabs/php_codesniffer --dev
  - composer require codeigniter4/codeigniter4-standard --dev
  

before_script:
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-source

after_success:
  - travis_retry php tests/bin/coveralls.phar